services:
  fastapi_app:
    build: .
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - ./logs:/var/log/summvideo   # Добавляем volume для логов
    restart: always