version: '3.8'

services:
  summvideo-app:
    build: .
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GIN_MODE: release
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/var/log/summvideo
    restart: always