name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    # Docker setup
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Log in to Docker Hub (если требуется)
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Сборка Docker-образа и (опционально) публикация в Docker Hub
    - name: Build Docker image
      run: docker build -t trofimov/myapp:latest .

    - name: Push Docker image to Docker Hub
      run: docker push trofimov/myapp:latest

    # Настройка SSH для доступа к серверу
    - name: Set up SSH for deployment
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    # Добавление SSH-ключа вашего сервера в файл known_hosts на runner-е (ваш сервер)
    - name: Add DigitalOcean Droplet to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 167.172.184.49 >> ~/.ssh/known_hosts

    # Добавление GitHub в known_hosts на сервере
    - name: Add GitHub to known_hosts on the Droplet
      run: |
        ssh root@167.172.184.49 "ssh-keyscan -H github.com >> ~/.ssh/known_hosts"

    # Деплой на сервер
    - name: Deploy to DigitalOcean Droplet
      run: |
        ssh root@167.172.184.49 << 'EOF'
          # Проверка существования папки и клонирование репозитория при необходимости
          if [ ! -d "/var/www/myapp/.git" ]; then
            rm -rf /var/www/myapp
            mkdir -p /var/www/myapp
            git clone git@github.com:trofimovm/summvideo.git /var/www/myapp
          fi
          cd /var/www/myapp

          # Получение последних изменений
          git pull origin main

          # Запуск Docker Compose
          docker-compose down
          docker-compose up -d --build
        EOF