name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checking out the repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t trofimov/myapp:latest .

    - name: Push Docker image to Docker Hub
      run: docker push trofimov/myapp:latest

    - name: Add server to known_hosts
      run: |
        ssh-keyscan 167.172.184.49 >> ~/.ssh/known_hosts

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy to server
      run: |
        ssh root@167.172.184.49 << EOF
          if [ ! -d "/var/www/myapp" ]; then
            mkdir -p /var/www/myapp
            git clone git@github.com:your-github-username/your-repository-name.git /var/www/myapp
          fi
          cd /var/www/myapp
          git pull origin main
          docker compose down
          docker compose up -d --build
        EOF